In [8]:
import glob 
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
import statsmodels.api as sm
import pingouin as pg

In [9]:
pd.options.display.max_columns = None 
pd.set_option('display.expand_frame_repr', False)

In [10]:
data_2020 = pd.read_csv('/Users/kathleenkanaley/Desktop/grapes_from_space/data/img_scout_dfs/2020/coreg_skysat_scout_2020.csv')

In [11]:
data_2020.head()

   acquired  plot      blue     green       red       nir  row  panel        Date  Treatment Block  PM_severity  DM_severity  total_dis                                           geometry                                       centroid
0  20200618     1  0.040044  0.077491  0.071216  0.353575    1      1  2020-06-18        5.0    PM          0.0         0.00       0.00  POLYGON ((-77.0152645742787 42.878300949250196...     POINT (-77.0153084903025 42.8783140936145)
1  20200618     2  0.044693  0.081807  0.077133  0.336587    1      2  2020-06-18        9.0    PM          0.0         0.05       5.05  POLYGON ((-77.01535545427274 42.87831851925121...    POINT (-77.0153965503027 42.87833067861654)
2  20200618     4  0.040121  0.076396  0.070693  0.343482    1      4  2020-06-18       18.0    PM          0.0         0.00       0.50  POLYGON ((-77.01552730426143 42.87835065925314...   POINT (-77.01557007030289 42.87836309362055)
3  20200618     5  0.034862  0.073497  0.060772  0.358279    1      5  2020-06-18        6.0    PM          0.0         0.00      15.10  POLYGON ((-77.01561588425558 42.87836680925413...  POINT (-77.01565649030296 42.878378758622546)
4  20200618     6  0.039300  0.075070  0.068893  0.337817    1      6  2020-06-18        2.0    PM          0.0         0.00       5.65  POLYGON ((-77.01570014425 42.878381989255075, ...   POINT (-77.01574402030295 42.87839504362453)

In [12]:
data_2020.acquired.unique()

array([20200618, 20200625, 20200710, 20200805, 20200812])

In [13]:
data_2020.describe()

           acquired        plot        blue       green         red         nir         row       panel   Treatment  PM_severity  DM_severity   total_dis
count  4.990000e+02  499.000000  499.000000  499.000000  499.000000  499.000000  499.000000  499.000000  499.000000        499.0   499.000000  499.000000
mean   2.020071e+07   85.771543    0.045098    0.068652    0.051428    0.338007    5.839679    8.336673   10.615230          0.0     1.859577    4.328214
std    8.378428e+01   47.898444    0.010482    0.009862    0.011395    0.054498    2.976877    4.478292    6.097291          0.0     4.482729    6.307813
min    2.020062e+07    1.000000    0.025230    0.046610    0.026124    0.243317    1.000000    1.000000    1.000000          0.0     0.000000    0.000000
25%    2.020062e+07   43.000000    0.036532    0.063367    0.047137    0.294178    3.000000    5.000000    5.000000          0.0     0.000000    0.350000
50%    2.020071e+07   97.000000    0.045307    0.068996    0.051466    0.335411    7.000000    8.000000   10.000000          0.0     0.050000    1.900000
75%    2.020080e+07  127.000000    0.051973    0.076372    0.059354    0.368198    8.000000   12.000000   15.000000          0.0     1.500000    5.425000
max    2.020081e+07  160.000000    0.071343    0.091057    0.084556    0.467090   10.000000   16.000000   24.000000          0.0    52.750000   52.750000

In [15]:
data_2020.iloc[3:10,3]

3    0.073497
4    0.075070
5    0.075070
6    0.072789
7    0.072527
8    0.073935
9    0.073935
Name: green, dtype: float64

In [22]:
data_2020[data_2020.row<7].shape

(249, 16)

In [27]:
data_2020["ndvi"] = (data_2020.nir-data_2020.red)/(data_2020.nir+data_2020.red)

In [28]:
data_2020

     acquired  plot      blue     green       red       nir  row  panel        Date  Treatment Block  PM_severity  DM_severity  total_dis                                           geometry                                       centroid      ndvi
0    20200618     1  0.040044  0.077491  0.071216  0.353575    1      1  2020-06-18        5.0    PM          0.0         0.00       0.00  POLYGON ((-77.0152645742787 42.878300949250196...     POINT (-77.0153084903025 42.8783140936145)  0.664702
1    20200618     2  0.044693  0.081807  0.077133  0.336587    1      2  2020-06-18        9.0    PM          0.0         0.05       5.05  POLYGON ((-77.01535545427274 42.87831851925121...    POINT (-77.0153965503027 42.87833067861654)  0.627123
2    20200618     4  0.040121  0.076396  0.070693  0.343482    1      4  2020-06-18       18.0    PM          0.0         0.00       0.50  POLYGON ((-77.01552730426143 42.87835065925314...   POINT (-77.01557007030289 42.87836309362055)  0.658633
3    20200618     5  0.034862  0.073497  0.060772  0.358279    1      5  2020-06-18        6.0    PM          0.0         0.00      15.10  POLYGON ((-77.01561588425558 42.87836680925413...  POINT (-77.01565649030296 42.878378758622546)  0.709953
4    20200618     6  0.039300  0.075070  0.068893  0.337817    1      6  2020-06-18        2.0    PM          0.0         0.00       5.65  POLYGON ((-77.01570014425 42.878381989255075, ...   POINT (-77.01574402030295 42.87839504362453)  0.661216
..        ...   ...       ...       ...       ...       ...  ...    ...         ...        ...   ...          ...          ...        ...                                                ...                                            ...       ...
494  20200812   154  0.033227  0.056373  0.036703  0.367113   10     10  2020-08-13       12.0    DM          0.0         0.60       0.60  POLYGON ((-77.01605999902254 42.87867018016665...   POINT (-77.0161013453033 42.878682743632794)  0.818218
495  20200812   155  0.029468  0.054482  0.033250  0.364829   10     11  2020-08-13        3.0    DM          0.0         0.25       0.25  POLYGON ((-77.0161457490169 42.8786865901676, ...  POINT (-77.01618532530341 42.878698738634725)  0.832948
496  20200812   157  0.028348  0.053731  0.030669  0.392379   10     13  2020-08-13        4.0    DM          0.0         0.20       0.20  POLYGON ((-77.0163147390058 42.87871901016951,...   POINT (-77.01635581030357 42.87873143863867)  0.855010
497  20200812   158  0.031935  0.059768  0.037213  0.380077   10     14  2020-08-13       16.0    DM          0.0         3.45       3.45  POLYGON ((-77.0163999390002 42.87873515017044,...  POINT (-77.01644346530357 42.878748438640656)  0.821645
498  20200812   159  0.034619  0.061459  0.038404  0.366478   10     15  2020-08-13        1.0    DM          0.0        24.20      24.20  POLYGON ((-77.0164900489943 42.878753010171465...  POINT (-77.01652978530375 42.878765158642686)  0.810297

[499 rows x 17 columns]

In [36]:
scipy.stats.ttest_1samp(data_2020.ndvi, popmean=0.9, alternative='greater')

/var/folders/hg/02pmwyy14wvgdv7n1gzwlx1w0000gn/T/ipykernel_2665/2125377622.py:1: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  scipy.stats.ttest_1samp(data_2020.ndvi, popmean=0.9, alternative='greater')

Ttest_1sampResult(statistic=inf, pvalue=0.0)

In [38]:
pg.ttest(data_2020.ndvi, 0.5)

/Users/kathleenkanaley/miniconda3/envs/planetenv/lib/python3.10/site-packages/pingouin/parametric.py:237: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  tval, pval = ttest_1samp(x, y, alternative=alternative)
/Users/kathleenkanaley/miniconda3/envs/planetenv/lib/python3.10/site-packages/pingouin/effsize.py:788: RuntimeWarning: divide by zero encountered in double_scalars
  d = (x.mean() - y) / x.std(ddof=1)
/Users/kathleenkanaley/miniconda3/envs/planetenv/lib/python3.10/site-packages/pingouin/parametric.py:280: RuntimeWarning: invalid value encountered in multiply
  ci = np.array([tval - tcrit, tval + tcrit]) * se

          T  dof alternative  p-val       CI95%  cohen-d BF10 power
T-test  inf  498   two-sided    0.0  [nan, nan]      inf  nan   NaN