In [2]:
import os
import glob
import rasterio as rio
from rasterio.mask import raster_geometry_mask
from rasterio import plot
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json
import pyproj
from shapely.geometry import shape, MultiPolygon
from shapely.ops import transform

In [11]:
# Functions

# Get panel masks

def get_panel_masks(geojson_path, ref_img_path):
    '''This function generates a mask that leaves only pixels inside 
    vine panels unmasked. 
    
    Inputs:
    geojson_path (str): path to a geojson file with the panel geometries. 
    Must be in same CRS as image, otherwise un-comment code section starting with "dst_crs".
    ref_img_path (str): path to the .tif file for the image
    
    Outputs:
    A list of masks, as Boolean arrays. True values are masked pixels.
    False values are unmasked pixels.
    '''
    with open(geojson_path, 'r') as f:
        panels = json.load(f)
        features = panels['features']
        features_ordered = sorted(features, key= lambda feature:(feature['properties']['row'],feature['properties']['panel'])) # ground truth order.
        panel_aois = [f['geometry'] for f in features_ordered]
    
    with rio.open(ref_img_path) as src:
        dst_crs = src.crs
        
        # geojson features (the field block geometries)
        # are often in WGS84
        # project these to the image coordinates
        wgs84 = pyproj.CRS('EPSG:4326')

        project = pyproj.Transformer.from_crs(wgs84, dst_crs, always_xy=True).transform
        proj_panel_aois = [transform(project, shape(p)) for p in panel_aois]

        masks = [raster_geometry_mask(src, [p], crop=False)[0]
                 for p in proj_panel_aois]                       
    return masks

# Get reflectance df

def get_rfl(img_path, masks):
    '''
    Function to extract per=panel reflectance values for 4-band SkySat images.
    Calculates the mean reflectance values for the pixels in each panel.
    The output is formatted as a pandas dataframe.
    
    Inputs:
    img_path - abs. path to the image       
    masks - a list of masks that correspond to the panel aois. 
    '''
    
    with rio.open(img_path,'r') as img:
        def _get_stats(mask, panel_number):
            panel_blue = np.ma.mean(np.ma.array(img.read(1), mask=mask))/10000
            panel_green = np.ma.mean(np.ma.array(img.read(2), mask=mask))/10000
            panel_red = np.ma.mean(np.ma.array(img.read(3), mask=mask))/10000
            panel_nir = np.ma.mean(np.ma.array(img.read(4), mask=mask))/10000
            
            return {'acquired': img_path.split('/')[-1].split('_')[-5], # date from image filename
                    'plot': panel_number + 1,    #add one - panels are numbered starting at 1 in the 'real world'
                    'blue': panel_blue,
                    'green': panel_green,
                    'red': panel_red,
                    'nir': panel_nir}
        data = [_get_stats(m, i) for i, m in enumerate(masks)]  # sets the parameters for the nested function as the mask (m) and corresponding panel number (i). 
        df = pd.DataFrame(data)
    
    return df

In [12]:
# image directory containing co-registered SkySat scenes 

img_dir = '../data/images/2021/SkySat/'

# image pathnames
img_paths = glob.glob(img_dir+'2021*.tif')

# geojson with panel geometries

json_path = '../data/crit_panels_geojson.geojson'
#json_path
img_paths

['../data/images/2021/SkySat/20210726_160338_ssc1d2_0013_ar.tif',
 '../data/images/2021/SkySat/20210802_184019_ssc10d2_0005_ar.tif',
 '../data/images/2021/SkySat/20210707_150122_ssc19d2_0016_ar.tif',
 '../data/images/2021/SkySat/20210816_171007_ssc18d2_0015_ar.tif',
 '../data/images/2021/SkySat/20210809_185329_ssc9d2_0014_ar.tif']

In [13]:
# Get dataframes for all images in directory

master_df = pd.DataFrame()

for i in img_paths:
    masks = get_panel_masks(json_path, i)
    df = get_rfl(i, masks)
    master_df = pd.concat([master_df, df], axis=0)
    master_df = master_df.sort_values(by=['acquired', 'plot'])

master_df

     acquired  plot      blue     green       red       nir
0    20210707     1  0.032006  0.066432  0.040084  0.290003
1    20210707     2  0.033528  0.067879  0.043324  0.270290
2    20210707     3  0.033903  0.067897  0.042947  0.273817
3    20210707     4  0.032868  0.067358  0.042055  0.280455
4    20210707     5  0.032104  0.066636  0.038836  0.292664
..        ...   ...       ...       ...       ...       ...
315  20210816   316  0.016079  0.064390  0.045383  0.246759
316  20210816   317  0.012997  0.062097  0.043137  0.247093
317  20210816   318  0.012376  0.061769  0.041824  0.254628
318  20210816   319  0.011006  0.059225  0.038784  0.253509
319  20210816   320  0.015918  0.065997  0.046033  0.257685

[1600 rows x 6 columns]

In [14]:
# Append corresponding row and panel numbers for each plot 

panel_csv = pd.read_csv('../data/crit_panels.csv')
cols = panel_csv.iloc[:,1:] # adjust this according to the .csv
#cols
appended = pd.concat([master_df, cols],axis=1)
appended

     acquired  plot      blue     green       red       nir  row  panel
0    20210707     1  0.032006  0.066432  0.040084  0.290003    1      1
1    20210707     2  0.033528  0.067879  0.043324  0.270290    1      2
2    20210707     3  0.033903  0.067897  0.042947  0.273817    1      3
3    20210707     4  0.032868  0.067358  0.042055  0.280455    1      4
4    20210707     5  0.032104  0.066636  0.038836  0.292664    1      5
..        ...   ...       ...       ...       ...       ...  ...    ...
315  20210816   316  0.016079  0.064390  0.045383  0.246759   20     12
316  20210816   317  0.012997  0.062097  0.043137  0.247093   20     13
317  20210816   318  0.012376  0.061769  0.041824  0.254628   20     14
318  20210816   319  0.011006  0.059225  0.038784  0.253509   20     15
319  20210816   320  0.015918  0.065997  0.046033  0.257685   20     16

[1600 rows x 8 columns]

In [15]:
appended.acquired.unique()

array(['20210707', '20210726', '20210802', '20210809', '20210816'],
      dtype=object)

In [16]:
scout_csv = pd.read_csv('../data/scout/scout_2021_gdf.csv')
scout_csv.Date.unique()

array(['2021-06-24', '2021-07-01', '2021-07-07', '2021-07-15',
       '2021-07-27', '2021-08-03', '2021-08-10', '2021-08-17'],
      dtype=object)

In [17]:
# Match scout data to image data

# Define filtering and matching parameters

first_row = 1
last_row = 20

match_dates = ['2021-07-07','2021-07-27', '2021-08-03', '2021-08-10', '2021-08-17']
match_cols =['row', 'panel', 'Date']


# Filter and join datasets

img_filtered = appended[appended['row']>=first_row]
img_filtered = img_filtered[img_filtered['row']<=last_row]

scout_filtered = scout_csv[scout_csv['Row']>=first_row]
scout_filtered = scout_csv[scout_csv['Row']<=last_row]

scout_filtered = scout_filtered[scout_filtered['Date'].isin(match_dates)]
scout_filtered = scout_filtered.rename(columns={'Row':'row', 'Panel':'panel'})
scout_filtered[["row", "panel"]] = scout_filtered[["row", "panel"]].apply(pd.to_numeric)

# Create a 'Date' column in the image dataframe to match the scout date
def match_days(row):
    if row['acquired']=='20210707':
        return '2021-07-07'
    if row['acquired']=='20210726':
        return '2021-07-27'
    if row['acquired']=='20210802':
        return '2021-08-03'
    if row['acquired']=='20210809':
        return '2021-08-10'
    if row['acquired']=='20210816':
        return '2021-08-17'

img_filtered['Date'] = img_filtered.apply(lambda row: match_days(row), axis=1)

# Join and drop NANs + unneeded columns

joined = img_filtered.join(scout_filtered.set_index(match_cols), on=match_cols)

cleaned = joined.dropna(axis=0,subset=['DM_severity'])
cleaned.info()
## Uncomment below for masked rasters
#no_nullpix = cleaned.dropna(axis=0,subset=['blue', 'green', 'red', 'nir'])

#no_nullpix.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1195 entries, 0 to 310
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   acquired     1195 non-null   object
 1   plot         1195 non-null   int64
 2   blue         1195 non-null   float64
 3   green        1195 non-null   float64
 4   red          1195 non-null   float64
 5   nir          1195 non-null   float64
 6   row          1195 non-null   int64
 7   panel        1195 non-null   int64
 8   Date         1195 non-null   object
 9   Treatment    1195 non-null   float64
 10  Block        1195 non-null   object
 11  PM_severity  1195 non-null   float64
 12  DM_severity  1195 non-null   float64
 13  total_dis    1195 non-null   float64
 14  geometry     1195 non-null   object
 15  centroid     1195 non-null   object
dtypes: float64(8), int64(3), object(5)
memory usage: 158.7+ KB

In [18]:
# Export dataframe as .csv

output_fp = '../data/img_scout_dfs/2021/'

#cleaned.to_csv(output_fp+'skysat_scout_2021.csv', index=False)

In [4]:
# Merge incidence data

inc = pd.read_csv('/Users/kathleenkanaley/Desktop/grapes_from_space/data/scout/scout_incidence/scout_inc_2021.csv')

other = pd.read_csv('/Users/kathleenkanaley/Desktop/grapes_from_space/data/img_scout_dfs/2021/skysat_scout_2021.csv')

In [5]:
print(inc.columns)
print(other.columns)

Index(['Date', 'Row', 'Panel', 'Treatment', 'Block', 'PM_severity',
       'DM_severity', 'total_dis', 'geometry', 'centroid', 'PM_inc', 'DM_inc'],
      dtype='object')
Index(['acquired', 'plot', 'blue', 'green', 'red', 'nir', 'row', 'panel',
       'Date', 'Treatment', 'Block', 'PM_severity', 'DM_severity', 'total_dis',
       'geometry', 'centroid'],
      dtype='object')

In [6]:
inc.rename(columns={"Row": "row", "Panel": "panel"}, inplace=True)
inc.columns

Index(['Date', 'row', 'panel', 'Treatment', 'Block', 'PM_severity',
       'DM_severity', 'total_dis', 'geometry', 'centroid', 'PM_inc', 'DM_inc'],
      dtype='object')

In [7]:
merged_2021 = other.merge(inc, how='left', on=['Date', 
                                               'row', 
                                               'panel',
                                               'Treatment', 
                                               'Block', 
                                               'PM_severity','DM_severity',
                                              'total_dis','geometry','centroid'])
merged_2021.shape

(1231, 18)

In [8]:
other.shape

(1195, 16)

In [10]:
merged_2021

,acquired,plot,blue,green,red,nir,row,panel,Date,Treatment,Block,PM_severity,DM_severity,total_dis,geometry,centroid,PM_inc,DM_inc
0,20210707,1,0.032006,0.066432,0.040084,0.290003,1,1,2021-07-07,5.0,DM,0.00,0.00,0.05,POLYGON ((-77.0152645742787 42.878300949250196...,POINT (-77.0153084903025 42.8783140936145),0.0,0.0
1,20210707,2,0.033528,0.067879,0.043324,0.270290,1,2,2021-07-07,7.0,DM,0.00,0.00,0.10,POLYGON ((-77.01535545427274 42.87831851925121...,POINT (-77.0153965503027 42.87833067861654),0.0,0.0
2,20210707,3,0.033903,0.067897,0.042947,0.273817,1,3,2021-07-07,9.0,DM,0.00,0.00,0.10,POLYGON ((-77.01544069426711 42.87833411925217...,POINT (-77.01548247530272 42.87834674861851),0.0,0.0
3,20210707,4,0.032868,0.067358,0.042055,0.280455,1,4,2021-07-07,15.0,DM,0.00,0.00,0.60,POLYGON ((-77.01552730426143 42.87835065925314...,POINT (-77.01557007030289 42.87836309362055),0.0,0.0
4,20210707,5,0.032104,0.066636,0.038836,0.292664,1,5,2021-07-07,3.0,DM,0.00,0.00,0.10,POLYGON ((-77.01561588425558 42.87836680925413...,POINT (-77.01565649030296 42.878378758622546),0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1226,20210816,303,0.017663,0.065519,0.048503,0.248441,19,15,2021-08-17,18.0,PM,13.20,0.00,13.20,POLYGON ((-77.01536426393243 42.87876078918534...,POINT (-77.01540822030267 42.878773523616815),90.0,5.0
1227,20210816,305,0.009077,0.061277,0.038242,0.256381,20,1,2021-08-17,31.0,PM,0.90,0.00,0.90,POLYGON ((-77.01658187329902 42.87901510909438...,POINT (-77.01662629530372 42.8790284536449),20.0,0.0
1228,20210816,307,0.009167,0.060350,0.038300,0.249923,20,3,2021-08-17,40.0,PM,16.60,0.25,17.05,POLYGON ((-77.0164079733105 42.878982759092416...,POINT (-77.01645016030366 42.87899534864085),85.0,0.0
1229,20210816,309,0.011672,0.062224,0.041776,0.253272,20,5,2021-08-17,14.0,PM,0.00,0.00,0.05,POLYGON ((-77.01623108332213 42.87894828909042...,POINT (-77.01627422530342 42.878961353636775),0.0,0.0
1230,20210816,311,0.010876,0.061076,0.039593,0.260190,20,7,2021-08-17,35.0,PM,20.05,0.00,20.45,POLYGON ((-77.01605814333348 42.87891530908846...,POINT (-77.01609963030329 42.87892805863273),95.0,0.0

In [11]:
merged_2021_nodup = merged_2021.drop_duplicates()
merged_2021_nodup.shape

(1195, 18)

In [12]:
other.shape

(1195, 16)

In [13]:
output_fp = '/Users/kathleenkanaley/Desktop/grapes_from_space/data/img_scout_dfs/'
#merged_2021_nodup.to_csv(output_fp+'2021/INC_skysat_scout_2021.csv', index=False)