In [3]:
import os
import glob
import rasterio as rio
from rasterio.mask import raster_geometry_mask
from rasterio import plot
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json
import pyproj
from shapely.geometry import shape, MultiPolygon
from shapely.ops import transform

In [8]:
# Functions

# Get panel masks

def get_panel_masks(geojson_path, ref_img_path):
    '''This function generates a mask that leaves only pixels inside 
    vine panels unmasked. 
    
    Inputs:
    geojson_path (str): path to a geojson file with the panel geometries. 
    Must be in same CRS as image, otherwise un-comment code section starting with "dst_crs".
    ref_img_path (str): path to the .tif file for the image
    
    Outputs:
    A list of masks, as Boolean arrays. True values are masked pixels.
    False values are unmasked pixels.
    '''
    with open(geojson_path, 'r') as f:
        panels = json.load(f)
        features = panels['features']
        features_ordered = sorted(features, key= lambda feature:(feature['properties']['row'],feature['properties']['panel'])) # ground truth order.
        panel_aois = [f['geometry'] for f in features_ordered]
    
    with rio.open(ref_img_path) as src:
        dst_crs = src.crs
        
        # geojson features (the field block geometries)
        # are often in WGS84
        # project these to the image coordinates
        wgs84 = pyproj.CRS('EPSG:4326')

        project = pyproj.Transformer.from_crs(wgs84, dst_crs, always_xy=True).transform
        proj_panel_aois = [transform(project, shape(p)) for p in panel_aois]

        masks = [raster_geometry_mask(src, [p], crop=False)[0]
                 for p in proj_panel_aois]                       
    return masks

# Get reflectance df

def get_rfl(img_path, masks):
    '''
    Function to extract per=panel reflectance values for 4-band SkySat images.
    Calculates the mean reflectance values for the pixels in each panel.
    The output is formatted as a pandas dataframe.
    
    Inputs:
    img_path - abs. path to the image       
    masks - a list of masks that correspond to the panel aois. 
    '''
    
    with rio.open(img_path,'r') as img:
        def _get_stats(mask, panel_number):
            panel_blue = np.ma.mean(np.ma.array(img.read(1), mask=mask))#/10000
            panel_green = np.ma.mean(np.ma.array(img.read(2), mask=mask))#/10000
            panel_red = np.ma.mean(np.ma.array(img.read(3), mask=mask))#/10000
            panel_nir = np.ma.mean(np.ma.array(img.read(4), mask=mask))#/10000
            veg_band= np.ma.mean(np.ma.array(img.read(5),mask=mask))
            ndvi = np.ma.mean(np.ma.array(img.read(6),mask=mask))
            evi = np.ma.mean(np.ma.array(img.read(7),mask=mask))
            arvi = np.ma.mean(np.ma.array(img.read(8),mask=mask))
            savi = np.ma.mean(np.ma.array(img.read(9),mask=mask))
            msavi = np.ma.mean(np.ma.array(img.read(10),mask=mask))
            msavi_exp = np.ma.mean(np.ma.array(img.read(11),mask=mask))
            gcc = np.ma.mean(np.ma.array(img.read(12),mask=mask))
            gri = np.ma.mean(np.ma.array(img.read(13),mask=mask))
            
            return {'acquired': img_path.split('/')[-1].split('_')[-8], # date from image filename
                    'plot': panel_number + 1,    #add one - panels are numbered starting at 1 in the 'real world'
                    'blue': panel_blue,
                    'green': panel_green,
                    'red': panel_red,
                    'nir': panel_nir,
                   'veg_smr': veg_band,
                    'ndvi': ndvi,
                    'evi': evi,
                    'arvi': arvi,
                    'savi': savi,
                    'msavi': msavi,
                    'msavi_exp': msavi_exp,
                    'gcc': gcc,
                    'gri': gri}
        
        data = [_get_stats(m, i) for i, m in enumerate(masks)]  # sets the parameters for the nested function as the mask (m) and corresponding panel number (i). 
        df = pd.DataFrame(data)
    
    return df

In [5]:
# image directory containing co-registered SkySat scenes 

img_dir = '../data/images/2022/SkySat/smr_vis_2022/'

# image pathnames
img_paths = glob.glob(img_dir+'*.tif')

# geojson with panel geometries

json_path = '../data/crit_panels_geojson.geojson'
json_path
img_paths

['../data/images/2022/SkySat/smr_vis_2022/SMR_VIs_20220622_160829_ssc15d2_0014_analytic_SR_corg_clipped.tif',
 '../data/images/2022/SkySat/smr_vis_2022/SMR_VIs_20220801_151508_ssc13d2_0011_analytic_SR_corg_clipped.tif',
 '../data/images/2022/SkySat/smr_vis_2022/SMR_VIs_20220720_153112_ssc4d2_0013_analytic_SR_clipped_clipped.tif']

In [7]:
img_paths[0].split('/')[-1].split('_')[-8]

'20220622'

In [9]:
# Get dataframes for all images in directory

master_df = pd.DataFrame()

for i in img_paths:
    masks = get_panel_masks(json_path, i)
    df = get_rfl(i, masks)
    master_df = pd.concat([master_df, df], axis=0)
    master_df = master_df.sort_values(by=['acquired', 'plot'])

master_df

,acquired,plot,blue,green,red,nir,veg_smr,ndvi,evi,arvi,savi,msavi,msavi_exp,gcc,gri
0,20220622,1,0.064216,0.096894,0.101359,0.370316,0.541185,0.570341,0.449359,0.456009,0.415183,0.293978,0.422106,0.369386,0.957620
1,20220622,2,0.065437,0.097030,0.104597,0.358477,0.504905,0.548477,0.424668,0.428080,0.395456,0.266402,0.396512,0.363375,0.928531
2,20220622,3,0.065977,0.097253,0.104310,0.355327,0.497562,0.546481,0.422489,0.427810,0.392434,0.261014,0.392264,0.363629,0.933402
3,20220622,4,0.064136,0.096182,0.101911,0.361721,0.521191,0.560539,0.435540,0.443312,0.404437,0.276967,0.408007,0.366826,0.944762
4,20220622,5,0.064762,0.095248,0.103503,0.353700,0.499395,0.547266,0.420352,0.426744,0.392062,0.259432,0.392226,0.361525,0.921422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,20220801,316,0.045276,0.068041,0.036614,0.511021,1.061427,0.866252,0.853081,0.896370,0.679161,0.763347,0.916250,0.454420,1.870422
316,20220801,317,0.048193,0.070327,0.039713,0.512520,1.051050,0.856093,0.850848,0.885170,0.673940,0.755298,0.896344,0.445038,1.777578
317,20220801,318,0.050507,0.069993,0.038648,0.508359,1.042938,0.858715,0.862897,0.900012,0.672929,0.746266,0.892634,0.440274,1.815890
318,20220801,319,0.044834,0.067684,0.037772,0.497063,1.030226,0.858771,0.828296,0.883859,0.665729,0.717330,0.883231,0.451067,1.799010
319,20220801,320,0.047827,0.071370,0.039279,0.510282,1.046511,0.857096,0.850280,0.886731,0.673067,0.749971,0.892987,0.451514,1.824252

In [10]:
# Append corresponding row and panel numbers for each plot 

panel_csv = pd.read_csv('../data/crit_panels.csv')
cols = panel_csv.iloc[:,1:] # adjust this according to the .csv
#cols
appended = pd.concat([master_df, cols],axis=1)
appended

,acquired,plot,blue,green,red,nir,veg_smr,ndvi,evi,arvi,savi,msavi,msavi_exp,gcc,gri,row,panel
0,20220622,1,0.064216,0.096894,0.101359,0.370316,0.541185,0.570341,0.449359,0.456009,0.415183,0.293978,0.422106,0.369386,0.957620,1,1
1,20220622,2,0.065437,0.097030,0.104597,0.358477,0.504905,0.548477,0.424668,0.428080,0.395456,0.266402,0.396512,0.363375,0.928531,1,2
2,20220622,3,0.065977,0.097253,0.104310,0.355327,0.497562,0.546481,0.422489,0.427810,0.392434,0.261014,0.392264,0.363629,0.933402,1,3
3,20220622,4,0.064136,0.096182,0.101911,0.361721,0.521191,0.560539,0.435540,0.443312,0.404437,0.276967,0.408007,0.366826,0.944762,1,4
4,20220622,5,0.064762,0.095248,0.103503,0.353700,0.499395,0.547266,0.420352,0.426744,0.392062,0.259432,0.392226,0.361525,0.921422,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,20220801,316,0.045276,0.068041,0.036614,0.511021,1.061427,0.866252,0.853081,0.896370,0.679161,0.763347,0.916250,0.454420,1.870422,20,12
316,20220801,317,0.048193,0.070327,0.039713,0.512520,1.051050,0.856093,0.850848,0.885170,0.673940,0.755298,0.896344,0.445038,1.777578,20,13
317,20220801,318,0.050507,0.069993,0.038648,0.508359,1.042938,0.858715,0.862897,0.900012,0.672929,0.746266,0.892634,0.440274,1.815890,20,14
318,20220801,319,0.044834,0.067684,0.037772,0.497063,1.030226,0.858771,0.828296,0.883859,0.665729,0.717330,0.883231,0.451067,1.799010,20,15
319,20220801,320,0.047827,0.071370,0.039279,0.510282,1.046511,0.857096,0.850280,0.886731,0.673067,0.749971,0.892987,0.451514,1.824252,20,16

In [11]:
appended.acquired.unique()

array(['20220622', '20220720', '20220801'], dtype=object)

In [12]:
scout_csv = pd.read_csv('../data/scout/scout_2022_gdf.csv')
scout_csv.Date.unique()

array(['2022-06-22', '2022-06-29', '2022-07-06', '2022-07-14',
       '2022-07-20', '2022-07-27', '2022-08-02', '2022-08-09',
       '2022-08-29'], dtype=object)

In [13]:
# Match scout data to image data

# Define filtering and matching parameters

first_row = 1
last_row = 20

match_dates = ['2022-06-22','2022-07-06', '2022-07-20']
match_cols =['row', 'panel', 'Date']


# Filter and join datasets

img_filtered = appended[appended['row']>=first_row]
img_filtered = img_filtered[img_filtered['row']<=last_row]

scout_filtered = scout_csv[scout_csv['Row']>=first_row]
scout_filtered = scout_csv[scout_csv['Row']<=last_row]

scout_filtered = scout_filtered[scout_filtered['Date'].isin(match_dates)]
scout_filtered = scout_filtered.rename(columns={'Row':'row', 'Panel':'panel'})
scout_filtered[["row", "panel"]] = scout_filtered[["row", "panel"]].apply(pd.to_numeric)

# Create a 'Date' column in the image dataframe to match the scout date
def match_days(row):
    if row['acquired']=='20220622':
        return '2022-06-22'
    if row['acquired']=='20220707':
        return '2022-07-06'
    if row['acquired']=='20220720':
        return '2022-07-20'

img_filtered['Date'] = img_filtered.apply(lambda row: match_days(row), axis=1)

# Join and drop NANs + unneeded columns

joined = img_filtered.join(scout_filtered.set_index(match_cols), on=match_cols)
cleaned = joined.dropna(axis=0,subset=['DM_severity'])

cleaned.info()
# Uncomment below for masked rasters
#no_nullpix = cleaned.dropna(axis=0,subset=['blue', 'green', 'red', 'nir'])

#no_nullpix.info()
#joined = joined.rename(columns={'mean_sev_top_bot':'DM_severity'})
#cleaned = joined.dropna(axis=0,subset=['geometry', 'Treatment', 'leaf_avg', 'centroid'])
#cleaned = cleaned.drop(['Disease'], axis=1)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 480 entries, 0 to 318
Data columns (total 25 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   acquired     480 non-null    object
 1   plot         480 non-null    int64
 2   blue         480 non-null    float64
 3   green        480 non-null    float64
 4   red          480 non-null    float64
 5   nir          480 non-null    float64
 6   veg_smr      480 non-null    float64
 7   ndvi         480 non-null    float64
 8   evi          480 non-null    float64
 9   arvi         480 non-null    float64
 10  savi         480 non-null    float64
 11  msavi        480 non-null    float64
 12  msavi_exp    480 non-null    float64
 13  gcc          480 non-null    float64
 14  gri          480 non-null    float64
 15  row          480 non-null    int64
 16  panel        480 non-null    int64
 17  Date         480 non-null    object
 18  Treatment    480 non-null    float64
 19  Block        480 non-null    object
 20  PM_severity  480 non-null    float64
 21  DM_severity  480 non-null    float64
 22  total_dis    480 non-null    float64
 23  geometry     480 non-null    object
 24  centroid     480 non-null    object
dtypes: float64(17), int64(3), object(5)
memory usage: 97.5+ KB

In [14]:
# Export dataframe as .csv

output_fp = '../data/img_scout_dfs/2022/'

#cleaned.to_csv(output_fp+'smr_vis_skysat_scout_2022.csv', index=False)

In [15]:
# Merge incidence data

inc = pd.read_csv('/Users/kathleenkanaley/Desktop/grapes_from_space/data/scout/scout_incidence/scout_inc_2022.csv')

other = pd.read_csv('/Users/kathleenkanaley/Desktop/grapes_from_space/data/img_scout_dfs/2022/smr_vis_skysat_scout_2022.csv')

inc.rename(columns={"Row": "row", "Panel": "panel"}, inplace=True)
inc.columns

Index(['Date', 'row', 'panel', 'Treatment', 'Block', 'PM_severity',
       'DM_severity', 'total_dis', 'geometry', 'centroid', 'DM_inc', 'PM_inc'],
      dtype='object')

In [16]:
merged_2022 = other.merge(inc, how='left', on=['Date', 
                                               'row', 
                                               'panel',
                                               'Treatment', 
                                               'Block', 
                                               'PM_severity','DM_severity',
                                              'total_dis','geometry','centroid'])
merged_2022.shape

(480, 27)

In [17]:
other.shape

(480, 25)

In [18]:
merged_2022.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 480 entries, 0 to 479
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   acquired     480 non-null    int64
 1   plot         480 non-null    int64
 2   blue         480 non-null    float64
 3   green        480 non-null    float64
 4   red          480 non-null    float64
 5   nir          480 non-null    float64
 6   veg_smr      480 non-null    float64
 7   ndvi         480 non-null    float64
 8   evi          480 non-null    float64
 9   arvi         480 non-null    float64
 10  savi         480 non-null    float64
 11  msavi        480 non-null    float64
 12  msavi_exp    480 non-null    float64
 13  gcc          480 non-null    float64
 14  gri          480 non-null    float64
 15  row          480 non-null    int64
 16  panel        480 non-null    int64
 17  Date         480 non-null    object
 18  Treatment    480 non-null    float64
 19  Block        480 non-null    object
 20  PM_severity  480 non-null    float64
 21  DM_severity  480 non-null    float64
 22  total_dis    480 non-null    float64
 23  geometry     480 non-null    object
 24  centroid     480 non-null    object
 25  DM_inc       480 non-null    float64
 26  PM_inc       480 non-null    float64
dtypes: float64(19), int64(4), object(4)
memory usage: 105.0+ KB

In [20]:
output_fp = '/Users/kathleenkanaley/Desktop/grapes_from_space/data/img_scout_dfs/'
#merged_2022.to_csv(output_fp+'2022/smr_vis_skysat_scout_2022.csv', index=False)